name: build_and_deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lint
        run: npm i -g lint
      - name: Lint code
        run: lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Test code
        run: npm test
  build:
   runs-on: ubuntu-latest
   needs: test
   steps:
     - name: Build code
       run: npm build
      