name: build_and_deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint code
        run: npm lint
      - name: Test code
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build code
        run: npm build
      