name: build_and_deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      run: npm lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      run: npm test
  build:
   runs-on: ubuntu-latest
   needs: test
   steps:
     run: npm build
      