name: build_and_deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install eslint
        run: npm install -g eslint
      - name: Install eslint-plugin-react
        run: npm install eslint-plugin-react@latest --save-dev
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build code
        run: npm build
      