name: build_and_deploy
on:
  pull-request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev/*"
    path-ignore:
      - ".github/workflows/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      