name: events
on:
  # Events that trigger workflows:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    # Event filters:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
    branches:
      - main
      - "dev/*"
    paths-ignore:
      - ".github/workflows/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Use action from Marketplace
      # https://github.com/marketplace
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      