name: echo_issues
on:
  issues:
    types: opened
  workflow_dispatch:
jobs:
  echo_issue:
    runs-on: ubuntu-latest
    steps:
      - name: echo GitHub context
        run: |
         echo "Open issues: ${{ github.event.repository.open_issues }}"
         echo "Issues url: ${{ github.event.repository.issues_url }}"
      