name: echo_issues
on:
  issues:
    types: opened
  workflow_dispatch:
jobs:
  echo_issue:
    runs-on: ubuntu-latest
    steps:
      - name: echo GitHub context
        run: echo "Open issues: ${{ github.open_issues }}\nIssues url: ${{ github.issues_url }}"
      