name: Issues
on:
  issues:
    types: opened
  workflow_dispatch:
jobs:
  echo_issue:
    runs-on: ubuntu-latest
    steps:
      # Contexts & Expressions
      # https://docs.github.com/en/actions/learn-github-actions/contexts
      # https://docs.github.com/en/actions/learn-github-actions/expressions
      - name: echo GitHub context
        run: |
         echo "Open issues: ${{ github.event.repository.open_issues }}"
         echo "Issues url: ${{ github.event.repository.issues_url }}"
      