name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: "The name of the deployable artifact"
        required: false
        default: dist-files
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Lsit files
        run: ls -lah
      - name: Output information
        run: echo "Deploying & uploading .."